# Generated by Django 4.1.7 on 2023-04-02 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learner_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='usertype',
            new_name='email',
        ),
    ]
