# Generated by Django 4.1.7 on 2023-04-12 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learner_management', '0002_rename_usertype_users_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personal_information',
            old_name='citizenship',
            new_name='profession',
        ),
        migrations.RemoveField(
            model_name='personal_information',
            name='disability',
        ),
        migrations.RemoveField(
            model_name='personal_information',
            name='employment_status',
        ),
        migrations.RemoveField(
            model_name='personal_information',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='personal_information',
            name='race',
        ),
        migrations.RemoveField(
            model_name='personal_information',
            name='title',
        ),
    ]
